#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

sketchybar --bar display=main \
	position=top \
	height=37 \
	padding_right=10 \
	padding_left=10 \
	blur_radius=50 \
	color=0x40000000

default=(
	padding_left=5
	padding_right=5
	icon.font="SF Pro:Semibold:14.0"
	label.font="SF Pro:Semibold:14.0"
	icon.color=0xffffffff
	label.color=0xffffffff
	icon.padding_left=4
	icon.padding_right=4
	label.padding_left=4
	label.padding_right=4
)
sketchybar --default "${default[@]}"

##### Adding Mission Control Space Indicators #####

SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")
for i in "${!SPACE_ICONS[@]}"; do
	sid="$(($i + 1))"
	space=(
		space="$sid"
		icon="${SPACE_ICONS[i]}"
		icon.padding_left=7
		icon.padding_right=7
		background.color=0x40ffffff
		background.corner_radius=5
		background.height=25
		label.drawing=off
		script="$PLUGIN_DIR/space.sh"
		click_script="yabai -m space --focus $sid"
	)
	sketchybar --add space space."$sid" left --set space."$sid" "${space[@]}"
done

##### Adding Left Items #####
source $ITEM_DIR/front_app.sh

##### Adding Right Items #####
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/ram.sh
source $ITEM_DIR/cpu.sh

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
